[package]
name = "fig-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fig-core.workspace = true
fig-sstable.workspace = true
fig-wal.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
fig-core.workspace = true
tempfile.workspace = true
rand.workspace = true
